package se.liu.ida.noahe116.tddd78.swarm.game;

public enum EntityType {
    PLAYER,
    ASTEROID,
    PROJECTILE_DEFAULT,
    PROJECTILE_RED_LASER,
    PROJECTILE_SPREAD,
    PROJECTILE_QUAD,
    COLLECTIBLE_SHIELD,
    COLLECTIBLE_SHIP,
    COLLECTIBLE_RED_LASER,
    COLLECTIBLE_SPREAD,
    COLLECTIBLE_QUAD,
}
